<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-2BBJT9H" failures="1" tests="3" name="test" time="74.143" errors="0" timestamp="2023-03-17T22:47:10 IST">
  <testcase classname="TestNG.LoginTestNG" name="VerifyAdmin" time="0.031"/>
  <testcase classname="TestNG.LoginTestNG" name="VerifyLogininFunctionalityWithCorrectData" time="23.645"/>
  <testcase classname="TestNG.LoginTestNG" name="VerifyLogininFunctionalityWithIncorrectData" time="1.057">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at TestNG.LoginTestNG.VerifyLogininFunctionalityWithIncorrectData(LoginTestNG.java:78)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- VerifyLogininFunctionalityWithIncorrectData -->
  <testcase classname="TestNG.Baseclass" name="@AfterTest aftertest" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterTest aftertest -->
  <testcase classname="TestNG.Baseclass" name="@BeforeTest beforeTest" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest beforeTest -->
</testsuite> <!-- test -->
